# Generated by Django 3.1.2 on 2021-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
