# Generated by Django 3.1.2 on 2021-03-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
                ('base_url', models.CharField(blank=True, max_length=64, null=True)),
                ('login_required', models.BooleanField(default=False)),
                ('anonymous_only', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=10)),
                ('new_tab', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
                ('base_url', models.CharField(blank=True, max_length=64, null=True)),
                ('login_required', models.BooleanField(default=False)),
                ('anonymous_only', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.menuitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
