# Generated by Django 3.1.2 on 2021-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuitems',
            name='new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submenuitems',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
